{% set name = "tifffile" %}
{% set version = "2020.2.16" %}
{% set sha256 = "f03b03c4863d232e746859ebdf36e3dfd974364d9944d884bc82b430b0d7290d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tifffile/tifffile-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.6
    - pip
    - numpy
    - msinttypes  # [win and py<36]
  run:
    - python >=3.6
    - {{ pin_compatible('numpy') }}
    - imagecodecs-lite >=2019.4.20

test:
  imports:
    - tifffile

about:
  home: https://github.com/blink1073/tifffile
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Read and write image data from and to TIFF files
